### ISSUE TITLE
Halfway through the tournament, the match entry switched from 15/10/-5 to -5/10/15. WTFFFFFFF

### ISSUE THREAD

**Issue by jonahgreenthal** [mostafab/neg5.main#72]

**Comment by jonahgreenthal** [comment]
This went away when I switched browsers, but it is the most bizarre damn thing.

**Comment by mostafab** [comment]
Would you be able to provide a screenshot? If you remember anything different or how to reproduce this issue, that would help as well. 

I'm not able to recreate this issue.

**Comment by jonahgreenthal** [comment]
I don't have a screenshot, but I'm unsure why that would help anyway — if my description of the phenomenon is unclear, I'll clarify it.

I also have no idea how to re-create it.

In case it matters, I'll mention that of the two tournaments we were working on yesterday — one for the upper division and one for the lower division, where "division" is the standard use of the term, not the one that really means "pool" — one was consistently showing up in the –5/10/15 order, while the other was mostly 15/10/–5 until this bug occurred. I found that bizarre.

**Comment by mostafab** [comment]
I fixed a bug related to this today, fairly sure it's the same problem. I'm going to close it. If you come across it again, feel free to reopen it.
