### ISSUE TITLE
Use math.js instead of self-written gcd function

### ISSUE THREAD

**Issue by rjaguar3** [mostafab/neg5.main#82]
I found a node.js module called [Math.js](http://mathjs.org/) that has math functions such as calculating GCD.  I think it would be safer to link to that library than writing buggy code to do GCD ourselves.  (The library is licensed under Apache license, not MIT, but I don't think that should be a problem if we just add math.js as a dependency.)

**Comment by mostafab** [comment]
I would be open to that, but I'd prefer not to bring in the entire javascript file when we only need the gcd function. 

It looks like there's a way to do [custom bundling](http://mathjs.org/docs/custom_bundling.html), but I think it requires CommonJS, which the front end doesn't make use of.

Further inspection reveals that the current implementation of gcd and [Math.js's implementation of gcd](https://github.com/josdejong/mathjs/blob/d7d25e83c835c3f060bff2e26e293710b61fc32b/lib/function/arithmetic/gcd.js#L183) are pretty much the same, except one is recursive.
